version: "2"

services:
  concert-diary-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "concert-diary-be"
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
