version: "3.3"

services:
  concert-diary-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "concert-diary-be"
    restart: unless-stopped
    ports:
      - "3000:3000"
